/**
 * templates.js — Template strings for every generated file
 *
 * Each export is a function that receives the user's config and returns
 * the full file content as a string.
 */

// ── Framework-aware helpers ─────────────────────────────────────────────

/**
 * Return the correct client-side env var prefix for the given config.
 * - Next.js: NEXT_PUBLIC_
 * - Vue / Nuxt / Vite: VITE_
 * - SvelteKit: PUBLIC_
 * - Python / Go / Rust / Express / other: '' (no prefix)
 */
function envPrefix(cfg) {
  const fw = cfg.frameworks || [];
  if (fw.includes('Next.js')) return 'NEXT_PUBLIC_';
  if (
    fw.includes('Vue') ||
    fw.includes('Nuxt') ||
    fw.includes('Vite')
  ) {
    return 'VITE_';
  }
  if (fw.includes('SvelteKit') || fw.includes('Svelte')) return 'PUBLIC_';
  // Python, Go, Rust, Express, and everything else: no prefix
  const lang = (cfg.language || '').toLowerCase();
  if (lang.includes('python') || lang.includes('go') || lang.includes('rust')) {
    return '';
  }
  if (fw.includes('Express') || fw.includes('Fastify') || fw.includes('Hono')) {
    return '';
  }
  // Default: no prefix for unknown stacks
  return '';
}

/**
 * Return the correct .env target filename for the project.
 * - Next.js: .env.local
 * - Everything else: .env
 */
function envTargetFile(cfg) {
  const fw = cfg.frameworks || [];
  if (fw.includes('Next.js')) return '.env.local';
  return '.env';
}

/**
 * Return framework-appropriate default dev port.
 */
function devPort(cfg) {
  const fw = cfg.frameworks || [];
  if (fw.includes('Next.js') || fw.includes('Express') || fw.includes('Fastify') || fw.includes('Hono')) return '3000';
  if (fw.includes('Django') || fw.includes('FastAPI')) return '8000';
  if (fw.includes('Flask')) return '5000';
  if (fw.includes('Vue') || fw.includes('Nuxt') || fw.includes('Vite') || fw.includes('SvelteKit') || fw.includes('Svelte')) return '5173';
  return '3000';
}

/**
 * Determine if this is a Python project.
 */
function isPython(cfg) {
  const lang = (cfg.language || '').toLowerCase();
  return lang === 'python' || lang.includes('python');
}

/**
 * Return framework-appropriate install command.
 */
function installCommand(cfg) {
  if (isPython(cfg)) {
    return 'pip install -r requirements.txt';
  }
  const fw = cfg.frameworks || [];
  // Go detection (future-proofing)
  const lang = (cfg.language || '').toLowerCase();
  if (lang === 'go' || lang.includes('go')) return 'go mod download';

  const pm = cfg.packageManager || 'npm';
  if (pm === 'npm') return 'npm install';
  if (pm === 'yarn') return 'yarn';
  return `${pm} install`;
}

/**
 * Return framework-appropriate dev server command.
 */
function devCommand(cfg) {
  const fw = cfg.frameworks || [];
  if (fw.includes('Django')) return 'python manage.py runserver';
  if (fw.includes('Flask')) return 'flask run';
  if (fw.includes('FastAPI')) return 'uvicorn main:app --reload';
  if (isPython(cfg)) return 'python main.py';

  const lang = (cfg.language || '').toLowerCase();
  if (lang === 'go' || lang.includes('go')) return 'go run .';

  const pm = cfg.packageManager || 'npm';
  if (pm === 'npm') return 'npm run dev';
  return `${pm} dev`;
}

// ─────────────────────────────────────────────────────────────────────────
// CLAUDE.md
// ─────────────────────────────────────────────────────────────────────────

export function claudeMd(cfg) {
  const stackLine = [cfg.language, ...cfg.frameworks, ...cfg.tools]
    .filter(Boolean)
    .join(', ');

  const dbSection =
    cfg.database !== 'none'
      ? `
## Database

- Provider: **${dbDisplayName(cfg.database)}**
- Always use parameterized queries — never interpolate user input into SQL.
- Put database helpers in \`lib/db\` or \`utils/db\`.
- Keep migration files in a \`migrations/\` or \`supabase/migrations/\` folder.
`
      : '';

  const authSection =
    cfg.auth !== 'none'
      ? `
## Authentication

- Auth provider: **${authDisplayName(cfg.auth)}**
- Protect server routes and API endpoints — never trust the client alone.
- Store session/token logic in a shared \`lib/auth\` module.
`
      : '';

  return `# CLAUDE.md — AI Assistant Instructions

> This file tells AI coding assistants (Claude, Cursor, Copilot, etc.)
> how to work with **${cfg.projectName}**.
> Generated by [create-vibe-app](https://girlcode.technology) on ${today()}.

## Project Overview

- **Name:** ${cfg.projectName}
- **Stack:** ${stackLine || 'Not specified'}
- **Package manager:** ${cfg.packageManager}

## Coding Guidelines

- Write clean, readable code with descriptive variable names.
- Add brief comments explaining the *why*, not just the *what*.
- Keep files small and focused — one component or utility per file.
- Use existing patterns in the codebase before inventing new ones.
- When adding a new dependency, explain why it is necessary.

## File Structure Conventions

- Pages / routes live in \`app/\` or \`pages/\`.
- Reusable UI components go in \`components/\`.
- Shared utilities go in \`lib/\` or \`utils/\`.
- Server-only code goes in \`server/\` or uses a \`.server.\` suffix.
- Environment variables are listed in \`.env.example\`.
${dbSection}${authSection}
## Deployment

- Target platform: **${deployDisplayName(cfg.deploy)}**
- Keep environment-specific config in \`.env\` files (never commit secrets).
- The production build command is usually \`${buildCmd(cfg)}\`.

## Important Rules

1. **Never commit secrets** — API keys, tokens, and passwords belong in \`.env\` only.
2. **Do not delete or overwrite existing files** without asking first.
3. **Run the linter / formatter** before finishing (\`${lintCmd(cfg)}\`).
4. **Explain your changes** in plain language so non-technical contributors can follow along.

---

*Powered by Girl Code | girlcode.technology*
`;
}

// ─────────────────────────────────────────────────────────────────────────
// .env.example
// ─────────────────────────────────────────────────────────────────────────

export function envExample(cfg) {
  const prefix = envPrefix(cfg);
  const envFile = envTargetFile(cfg);
  const port = devPort(cfg);

  let lines = [
    '# ============================================',
    `# ${cfg.projectName} — Environment Variables`,
    '# ============================================',
    '#',
    `# Copy this file to ${envFile} and fill in real values.`,
    '# NEVER commit your actual .env file to git!',
    '#',
    `# Generated by create-vibe-app on ${today()}`,
    '',
  ];

  // Database
  if (cfg.database === 'supabase') {
    lines.push(
      '# ── Supabase ──────────────────────────────────',
      `${prefix}SUPABASE_URL=https://YOUR_PROJECT.supabase.co`,
      `${prefix}SUPABASE_ANON_KEY=your-anon-key-here`,
      'SUPABASE_SERVICE_ROLE_KEY=your-service-role-key-here',
      ''
    );
  } else if (cfg.database === 'turso') {
    lines.push(
      '# ── Turso / SQLite ────────────────────────────',
      'TURSO_DATABASE_URL=libsql://your-db-name-your-org.turso.io',
      'TURSO_AUTH_TOKEN=your-auth-token-here',
      ''
    );
  } else if (cfg.database === 'neon') {
    lines.push(
      '# ── Neon PostgreSQL ───────────────────────────',
      'DATABASE_URL=postgresql://user:password@host/dbname?sslmode=require',
      ''
    );
  } else if (cfg.database === 'mongodb') {
    lines.push(
      '# ── MongoDB Atlas ─────────────────────────────',
      'MONGODB_URI=mongodb+srv://user:password@cluster.mongodb.net/dbname',
      ''
    );
  } else if (cfg.database === 'firebase') {
    lines.push(
      '# ── Firebase ──────────────────────────────────',
      `${prefix}FIREBASE_API_KEY=your-api-key`,
      `${prefix}FIREBASE_AUTH_DOMAIN=your-project.firebaseapp.com`,
      `${prefix}FIREBASE_PROJECT_ID=your-project-id`,
      ''
    );
  }

  // Auth (only if different from DB provider)
  if (cfg.auth === 'clerk') {
    lines.push(
      '# ── Clerk Auth ────────────────────────────────',
      `${prefix}CLERK_PUBLISHABLE_KEY=pk_test_...`,
      'CLERK_SECRET_KEY=sk_test_...',
      ''
    );
  } else if (cfg.auth === 'nextauth') {
    lines.push(
      '# ── NextAuth / Auth.js ────────────────────────',
      `NEXTAUTH_URL=http://localhost:${port}`,
      'NEXTAUTH_SECRET=generate-a-random-string-here',
      ''
    );
  } else if (cfg.auth === 'supabase' && cfg.database !== 'supabase') {
    lines.push(
      '# ── Supabase Auth ─────────────────────────────',
      `${prefix}SUPABASE_URL=https://YOUR_PROJECT.supabase.co`,
      `${prefix}SUPABASE_ANON_KEY=your-anon-key-here`,
      ''
    );
  }

  // Generic app vars
  lines.push(
    '# ── App ───────────────────────────────────────',
    `${prefix}APP_URL=http://localhost:${port}`,
    ''
  );

  // Stripe placeholder (common in vibe-coded apps)
  lines.push(
    '# ── Payments (optional) ───────────────────────',
    '# STRIPE_SECRET_KEY=sk_test_...',
    `# ${prefix}STRIPE_PUBLISHABLE_KEY=pk_test_...`,
    ''
  );

  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────
// CONTRIBUTING.md
// ─────────────────────────────────────────────────────────────────────────

export function contributingMd(cfg) {
  const install = installCommand(cfg);
  const dev = devCommand(cfg);
  const envFile = envTargetFile(cfg);
  const port = devPort(cfg);

  return `# Contributing to ${cfg.projectName}

> Welcome! You do **not** need to be a professional developer to contribute.
> This guide is written for people who are learning as they go. You belong here.

## Getting Started

1. **Fork this repo** — click the "Fork" button on GitHub (top right).
2. **Clone your fork** to your computer:
   \`\`\`bash
   git clone https://github.com/YOUR_USERNAME/${cfg.projectName}.git
   cd ${cfg.projectName}
   \`\`\`
3. **Install dependencies:**
   \`\`\`bash
   ${install}
   \`\`\`
4. **Copy the example environment file:**
   Copy the file \`.env.example\` and rename the copy to \`${envFile}\`.
   Then open \`${envFile}\` and fill in the values (ask a maintainer if unsure).
5. **Start the development server:**
   \`\`\`bash
   ${dev}
   \`\`\`
   Open [http://localhost:${port}](http://localhost:${port}) in your browser.

## Making Changes

1. **Create a new branch** for your change:
   \`\`\`bash
   git checkout -b my-feature
   \`\`\`
   Name it something descriptive, like \`add-about-page\` or \`fix-login-button\`.

2. **Make your edits.** Save your files.

3. **Test your changes** by looking at them in the browser.

4. **Commit your work:**
   \`\`\`bash
   git add .
   git commit -m "Add about page"
   \`\`\`

5. **Push to GitHub:**
   \`\`\`bash
   git push origin my-feature
   \`\`\`

6. **Open a Pull Request (PR)** — go to the original repo on GitHub and
   click "Compare & pull request."

## Tips

- **Small PRs are better.** Change one thing at a time.
- **Ask questions!** Open an issue or leave a comment if you are stuck.
- **Write a clear PR description** — explain *what* you changed and *why*.
- **Be kind.** We are all learning.

## Code of Conduct

Be respectful, inclusive, and supportive. We follow the
[Contributor Covenant](https://www.contributor-covenant.org/) code of conduct.

---

*Powered by Girl Code | girlcode.technology*
`;
}

// ─────────────────────────────────────────────────────────────────────────
// .gitignore
// ─────────────────────────────────────────────────────────────────────────

export function gitignore(cfg) {
  const fw = cfg.frameworks || [];

  const lines = [
    '# ── Dependencies ──────────────────────────────',
    'node_modules/',
    '.pnp/',
    '.pnp.js',
    '',
    '# ── Build output ──────────────────────────────',
    '.next/',
    'out/',
    'dist/',
    'build/',
    '.vercel/',
    '.netlify/',
    '.turbo/',
    '',
    '# ── Environment variables (secrets!) ──────────',
    '.env',
    '.env.local',
    '.env.development.local',
    '.env.test.local',
    '.env.production.local',
    '',
    '# ── IDE / OS ──────────────────────────────────',
    '.vscode/',
    '.idea/',
    '*.swp',
    '*.swo',
    '.DS_Store',
    'Thumbs.db',
    '',
    '# ── Debug / logs ──────────────────────────────',
    'npm-debug.log*',
    'yarn-debug.log*',
    'yarn-error.log*',
    '.pnpm-debug.log*',
    '*.log',
    '',
    '# ── Test coverage ─────────────────────────────',
    'coverage/',
    '',
    '# ── TypeScript ────────────────────────────────',
    '*.tsbuildinfo',
    'next-env.d.ts',
    '',
  ];

  // SvelteKit extras
  if (fw.includes('SvelteKit') || fw.includes('Svelte')) {
    lines.push(
      '# ── SvelteKit ─────────────────────────────────',
      '.svelte-kit/',
      ''
    );
  }

  // Nuxt extras
  if (fw.includes('Nuxt')) {
    lines.push(
      '# ── Nuxt ──────────────────────────────────────',
      '.nuxt/',
      '.output/',
      ''
    );
  }

  // Python extras
  if (
    cfg.language === 'Python' ||
    cfg.language.includes('Python')
  ) {
    lines.push(
      '# ── Python ────────────────────────────────────',
      '__pycache__/',
      '*.py[cod]',
      '*$py.class',
      '.venv/',
      'venv/',
      'env/',
      '.eggs/',
      '*.egg-info/',
      ''
    );
  }

  // Supabase
  if (cfg.database === 'supabase') {
    lines.push(
      '# ── Supabase local ────────────────────────────',
      'supabase/.temp/',
      ''
    );
  }

  return lines.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────

function today() {
  return new Date().toISOString().split('T')[0];
}

function dbDisplayName(key) {
  const map = {
    supabase: 'Supabase (PostgreSQL)',
    turso: 'Turso (SQLite)',
    neon: 'Neon (PostgreSQL)',
    mongodb: 'MongoDB Atlas',
    firebase: 'Firebase Firestore',
    other: 'TBD',
  };
  return map[key] || key;
}

function authDisplayName(key) {
  const map = {
    supabase: 'Supabase Auth',
    clerk: 'Clerk',
    nextauth: 'NextAuth / Auth.js',
    firebase: 'Firebase Auth',
    other: 'TBD',
  };
  return map[key] || key;
}

function deployDisplayName(key) {
  const map = {
    vercel: 'Vercel',
    netlify: 'Netlify',
    railway: 'Railway',
    flyio: 'Fly.io',
    aws: 'AWS / Cloud',
    undecided: 'TBD',
  };
  return map[key] || key;
}

function buildCmd(cfg) {
  const pm = cfg.packageManager || 'npm';
  if (cfg.frameworks.includes('Next.js')) {
    return pm === 'npm' ? 'npm run build' : `${pm} build`;
  }
  return pm === 'npm' ? 'npm run build' : `${pm} build`;
}

function lintCmd(cfg) {
  const pm = cfg.packageManager || 'npm';
  return pm === 'npm' ? 'npm run lint' : `${pm} lint`;
}
